
version: '3.8'
services:
  pg_sap_data:
    image: postgres:15.3
    container_name: pg_sap_data
    
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - 5432:5432

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"

volumes:
  pg_sap_data:
    driver: local
  grafana:
    driver: local
